use_frameworks!

target 'SimpleSwiftNumericKeyboard_Example' do
  pod 'SimpleSwiftNumericKeyboard', :path => '../'

  target 'SimpleSwiftNumericKeyboard_Tests' do
    inherit! :search_paths

    
  end
end
